version: '3'
services:
  web:
    build:
        dockerfile: php_apache/Dockerfile
        context: .
    ports:
     - "80:80"
    depends_on:
     - db
    volumes: # for debugging
     - ./src/html:/var/www/html
  db:
    build:
        dockerfile: mysql/Dockerfile
        context: .
    ports:
     - "3306:3306"
    environment:
        # MYSQL_DATABASE: $DB_NAME
        MYSQL_ROOT_PASSWORD: $PASSWORD
        MYSQL_USER: $USER_NAME
        MYSQL_PASSWORD: $USER_PASS