version: '3'
services:
  web:
    build:
        dockerfile: php_apache/Dockerfile
        context: .
        args:
            MYSQL_USER: $USER_NAME
            MYSQL_PASSWORD: $USER_PASSWORD
    ports:
     - "80:80"
    depends_on:
     - db
    volumes: # for debugging
     - ./src/html:/var/www/html
  db:
    build:
        dockerfile: mysql/Dockerfile
        context: .
    environment:
        MYSQL_ROOT_PASSWORD: $ROOT_PASSWORD
        MYSQL_USER: $USER_NAME
        MYSQL_PASSWORD: $USER_PASSWORD
    container_name: bbs_db
